### ISSUE TITLE
Video link for NaviFields doesn't work

### ISSUE THREAD

**Issue by niallw** [locomotionvault/locomotionvault#1]
The NaviFields video listed on its summary card (https://www.youtube.com/watch?v=weo7cstIPSQ) doesn't work. It brings me to a youtube page that says "Video unavailable" (See image below). Is the video perhaps private and needs to be made public/unlisted for others to view it? A quick Google search yields the conference presentation video (https://www.youtube.com/watch?v=xv3jPzV0asI); not sure if that is what you wanted to link to on the website or not.

![image](https://user-images.githubusercontent.com/12411434/103469776-0b1e3080-4d37-11eb-85d7-3535b1662da9.png)

**Comment by locomotionvault** [comment]
Thanks @niallw for letting us know. It seems that the previous video is not on Youtube anymore. Linking to the conference paper makes sense. Can you send a pull request to check the link? That way you'll get the credit for contributing to the project (instead of us making the change).
